# Generated by Django 4.2.4 on 2023-09-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_cart_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stock_status',
        ),
    ]
